version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - prealloc
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - misspell
    - goconst

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
